CREATE TABLE IF NOT EXISTS ls_script (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_uuid VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(255),
    content CLOB,
    transcript CLOB,
    source_platform VARCHAR(32),
    external_id VARCHAR(128),
    stats_json CLOB,
    status VARCHAR(20) NOT NULL,
    heat_score DOUBLE PRECISION DEFAULT 0,
    heat_level VARCHAR(2) DEFAULT 'D',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ls_script_source_platform ON ls_script (source_platform);
CREATE INDEX IF NOT EXISTS idx_ls_script_status ON ls_script (status);
CREATE INDEX IF NOT EXISTS idx_ls_script_heat_level ON ls_script (heat_level);

CREATE TABLE IF NOT EXISTS ls_logic_fragment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_uuid VARCHAR(64) NOT NULL,
    f_type VARCHAR(20) NOT NULL,
    content CLOB NOT NULL,
    logic_desc CLOB,
    embedding CLOB,
    confidence DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ls_logic_fragment_script_uuid ON ls_logic_fragment (script_uuid);
CREATE INDEX IF NOT EXISTS idx_ls_logic_fragment_type ON ls_logic_fragment (f_type);

CREATE TABLE IF NOT EXISTS ls_generation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    reference_uuids CLOB,
    ai_output CLOB NOT NULL,
    user_edit CLOB,
    score INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ls_generation_log_created_at ON ls_generation_log (created_at);

CREATE TABLE IF NOT EXISTS ls_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    category VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, category)
);

CREATE INDEX IF NOT EXISTS idx_ls_tag_category ON ls_tag (category);

CREATE TABLE IF NOT EXISTS ls_script_tag (
    script_uuid VARCHAR(64) NOT NULL,
    tag_id BIGINT NOT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'AI',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (script_uuid, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_ls_script_tag_tag_id ON ls_script_tag (tag_id);
